#!/bin/bash
TWTRUNKDIR=$HOME/Documents/TiddlyWiki/Trunk
DEFAULT_FILENAME=index
FILENAME=${1:-$DEFAULT_FILENAME}
DEST=$PWD
RECIPE=$PWD/$FILENAME.html.recipe
ruby -Ku -C $TWTRUNKDIR/tools/cooker cook.rb $RECIPE -d$DEST $2 $3 $4 $5
