#!/bin/bash
TW_TRUNKDIR=${TW_TRUNKDIR:-$HOME/Documents/TiddlyWiki/Trunk}
DEFAULT_FILENAME=index
FILENAME=${1:-$DEFAULT_FILENAME}
FILENAME=${FILENAME%\.recipe}
FILENAME=${FILENAME%\.html}
DEST=$PWD
RECIPE=$PWD/$FILENAME.html.recipe
ruby -C $TW_TRUNKDIR/tools/cooker cook.rb $RECIPE -d$DEST -r$TW_TRUNKDIR $2 $3 $4 $5
